### ISSUE TITLE
How to run this in windows conda?

### ISSUE THREAD

**Issue by bitcoin5000** [NVIDIA/flowtron#61]
Can someone help run this in windows conda?
i spent 2 days trying do this, its install requrements.txt but give numpy or glow errors, 
i try different versions of tesflow and numpy nothing works :(

python inference.py -c config.json -f models/flowtron_ljs.pt -w models/waveglow_256channels_ljs_v3.pt -t "It is well know that deep generative models have a deep latent space!" -i 0

Traceback (most recent call last):
  File "inference.py", line 36, in <module>
    from glow import WaveGlow
ImportError: cannot import name 'WaveGlow'

**Comment by CookiePPP** [comment]
https://github.com/NVIDIA/flowtron#setup

Can you confirm
`git submodule update --init; cd tacotron2; git submodule update --init`
has been ran?

**Comment by bitcoin5000** [comment]
> git submodule update --init; cd tacotron2; git submodule update --init

this command seems not working in windows
ImportError: cannot import name 'WaveGlow'

(flowtron) Z:\NeuralVoice\flowtron-master>git submodule update --init
fatal: not a git repository (or any of the parent directories): .git

(flowtron) Z:\NeuralVoice\flowtron-master>cd tacotron2

(flowtron) Z:\NeuralVoice\flowtron-master\tacotron2>git submodule update --init
fatal: not a git repository (or any of the parent directories): .git

**Comment by bitcoin5000** [comment]
ITS WORKING ! Thanks! I forget put waveglow and right folder!

**Comment by CookiePPP** [comment]
ah, I assume you downloaded the code as a `.zip` instead of using
`git clone https://github.com/NVIDIA/flowtron.git`.

I'm not sure how to fix that.
(Option 1)
- You can move your checkpoints to a safe location. Delete `waveflow-master` and run `git clone https://github.com/NVIDIA/flowtron.git`. (and install [git](https://github.com/git-for-windows/git/releases/download/v2.28.0.windows.1/Git-2.28.0-64-bit.exe) if you haven't already). And move move your checkpoints back into the git-created `flowtron` folder.
- You can download the invidual zips from [here](https://github.com/NVIDIA/tacotron2) and [here](https://github.com/NVIDIA/waveglow) and drop the contents into the appropriate folders manually.
