### ISSUE TITLE
what is the purpose of gate_layer?

### ISSUE THREAD

**Issue by kurbobo** [NVIDIA/flowtron#68]
I haven't found it in the paper

**Comment by CookiePPP** [comment]
The gate layer will predict the end of the audio file.

This is used because alternatives like "end the audio file when the last letter is spoken" doesn't work for right-to-left languages or cases where the last char isn't used
e.g:
> This is a sentence?!

the model would never _speak_ the exclamation mark so that can't be detected in the attention map and used to identify when to stop speaking.

**Comment by eniolasonowo** [comment]
**Check MODEL ACHITECTURE in the paper**:
Finally, we add a dense layer with a sigmoid output the
flow step closest to z. This provides the model with a gating
mechanism as early as possible during inference to avoid
extra computation.
